[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fake-useragent>=2.2.0",
    "requests>=2.32.3",
    "selenium==4.27.1",
    "free_proxy>=1.1.3",
    "fp>=0.2",
]
